### ISSUE TITLE
Section Formatting

### ISSUE THREAD

**Issue by lisamarie616** [learn-co-curriculum/yield-and-blocks#14]
Hi there! This section is set up as a reading

![screenshot1](https://cloud.githubusercontent.com/assets/12042459/11406586/ecd15136-9362-11e5-853a-44578c6efd51.png)

but includes a code along, which is usually set up as a lab

![screen shot 2015-11-25 at 10 53 04 am](https://cloud.githubusercontent.com/assets/12042459/11406650/4d590ec2-9363-11e5-9ed1-8403c0d0edc3.png)

I went ahead and selected "View on GitHub" to fork and clone, but thought I should still raise this issue in case changing it to a lab format makes it easier for others to understand. :)

**Comment by AnnJohn** [comment]
Hi @lisamarie616 thanks for raising this issue! We went ahead and updated it to a lab  so should be all set. Thanks again.
