### ISSUE TITLE
invalid link to resource

### ISSUE THREAD

**Issue by survivingknowledge** [learn-co-curriculum/yield-and-blocks#23]
Coda Hale's Blog - Writing a Method that Uses Code Blocks
http://blog.codahale.com/2005/11/24/a-ruby-howto-writing-a-method-that-uses-code-blocks/

this link no longer is valid

**Comment by Joll59** [comment]
@survivingknowledge Thank you, invalid link deleted. New Resource Link will be provided. 

Closing issue for now.
