### ISSUE TITLE
Code along doesn't pass with the code given in lesson

### ISSUE THREAD

**Issue by reb3cca** [learn-co-curriculum/yield-and-blocks#25]
This lesson contains a code along lab. However, the code given to code along with during the lesson doesn't pass the tests. Initially, I assumed the error was mine—maybe I transposed two letters or made some other transcription error. But when I copied and pasted all of the code directly from the lesson to the IDE, it failed every test. 

I took apart the code and modified it until it passed all of the tests—without altering the tests and still using yield—so I feel like I still met the larger objective. But I still wanted to point out that this is going to fail for other students.

**Comment by Traci7822** [comment]
Issue still persists, student had the same issue and all of his code was correct.

**Comment by daniellecroxton** [comment]
+1 Having same issue.

**Comment by Joll59** [comment]
@reb3cca @danikrist @Traci7822 Thank you. Glad you were able to figure out a solution if the problem persists please ask a question using Slack or the ask a question feature on Learn.co. 
If the issue persists, screen cap your code and include in this conversation. 

Closing issue for now.
