### ISSUE TITLE
hello_spec.rb discrepancy 

### ISSUE THREAD

**Issue by m00se333** [learn-co-curriculum/yield-and-blocks#4]
There was a problem in the hello_spec.rb file. Initially the hello.rb file gives us this:

```
def hello

end

#call your method here
```

Yet when you pass this method an argument and iterate through the array correctly it still returns an error because the .spec file is testing for a `hello_t` method not a `hello` method, take a look.

```
Failures:

  1) #hello takes in an argument of an array and puts out a greeting to each person in the array whose name begins with the letter T
     Failure/Error: expect{hello_t(array){|name| puts "Hi, #{name}" if name.start_with?('T') }}.to output("Hi, Tim\nHi, Tom\n").to_stdout
     NoMethodError:
       undefined method `hello_t' for #<RSpec::ExampleGroups::Hello:0x007fc97c1822a0>
```

So what I did was I went into the hello.spec file and changed the test to look for a method named `hello` like the lab was started and not `hello_t` magiks.

Aside from that thanks for addressing the lack of `yield` before we hit the My_each, collect, select labs. Although I think now you're giving away how to complete the My_Each lab in the Yield and Blocks lab.

**Comment by AnnJohn** [comment]
Hi @m00se333 yes, sorry about that. We'll update the Readme to reflect hello_t. 

And for yields, we are being very "hand holdy" about how to build yield methods.
