### ISSUE TITLE
README.md - confusing wording "Your test should be passing" - requires more work in 'advanced'

### ISSUE THREAD

**Issue by mjhough** [learn-co-curriculum/yield-and-blocks#42]
Near the end of the README.md file, it says this:

"Here, we tell our method to return the original array simply by having that array be the last line of the method. Whatever is evaluated last in a method will be the return value for the whole method. **If you run the test again, you should be passing.**"

The bold words are confusing, because if you run learn again, the individual test is passing but not the whole test.

The fact that the next part says **'ADVANCED'** compounds the confusion. In all previous labs, this section was not required to complete all the learn tests. Yet in this one, it is.

I think this confuses the learner. It looks like the advanced section was added as a test later on, and README.md hasn't been changed to reflect that.

**Comment by sgharms** [comment]
Folding into #47

**Comment by sgharms** [comment]
Added a clarifying distinction between "test" and "test suite."
