### ISSUE TITLE
README.md Error - |i| was not used. Creates confusion.

### ISSUE THREAD

**Issue by mjhough** [learn-co-curriculum/yield-and-blocks#43]
The final paragraph in README.md states this:

"In the code-along above, we built our own implementation of the #each method. We used while to iterate through each element of the array and passed, or yielded, each successive element to an accompanying block. **That block used a parameter placeholder, |i|, to set a variable, i, equal to whatever value is yielded into the block at each step of the iteration.** That block also contained code to execute with each yielded element in turn."

Yet, the code examples use |name|. This confuses the reader and may prevent learners from understanding the lesson.

**Comment by sgharms** [comment]
Folding into #47

**Comment by sgharms** [comment]
Good catch, integrated.
