### ISSUE TITLE
Content Related Links

### ISSUE THREAD

**Issue by joshuaneedham** [learn-co-curriculum/yield-and-blocks#45]
There are a few links at the bottom of this lesson and they are not pointing to the correct end points.

Link #1 Correction
[All About Ruby - Ruby Blocks](https://allaboutruby.wordpress.com/2006/01/20/ruby-blocks-101/)
https://allaboutruby.wordpress.com/20https://allaboutruby.wordpress.com/2006/01/20/ruby-blocks-101/06/01/20/ruby-blocks-101/

Link #2 It appears that about.com has been changed quite a bit and I couldn't find a good link to replace it.

The other two links appear to be ok.

**Comment by curiositypaths** [comment]
Hi There,

Thank you for notifying us. We removed the broken link.

As always, thank you for contributing 💙
